server:
    port: 8080

management:
    endpoint:
        health:
            probes:
                enabled: true

#POSTGRE CONNECTIONS
spring:
    jpa:
        hibernate:
            ddl-auto: update
    datasource:
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
        password: root